### ISSUE TITLE
Code Peer Review 

### ISSUE THREAD

**Issue by BibianaLee** [UOA-MEDSCI-736/CallumChalmers29-crispy-disco#13]
Hi Callum, 

What was good:
- logical use of functions and user input 
- easy to follow 
- creative use of skills we learned in class 
- well commented 
- Your whole code seems user-friendly which is nice 

what could be improved: 
- licensing information at the beginning of the file 
- some segments of code didn't have comments but that's probably because you're still working on it 

Overall I really liked it :) good job!

**Comment by CallumChalmers29** [comment]
Hi Bibiana,

Thanks for your feedback, I have added the licensing info in the docstring at the top of the programme and have updated all functions so they are appropriately commented. If you could have a look once my pull request is granted, that would be great :)

Thanks
Callum

**Comment by BibianaLee** [comment]
Hey Callum, 

The request hasn't been granted yet but I'm happy with the changes you've made! 
Ima close the issue :) 

Thank you, 

Bibiana
