### ISSUE TITLE
DMP peer review

### ISSUE THREAD

**Issue by dvasques83** [UOA-MEDSCI-736/CallumChalmers29-crispy-disco#17]
Hi Callum, I'm sorry it took ages to give you my feedback on that.
Your DMP is pretty neat and tidy. I believe all important info is well explained and clear. Just one minor observation:

In ethics requirementsI would try to explain what kind of data you are using and why it is not sensitive. You have already stated that it is open access, so perhaps would be interesting to detail a little the information it carries that makes it free of ethical issues.

Very nice work!
Cheers,

Demi

**Comment by CallumChalmers29** [comment]
Hi Demi,

Thanks for your feedback, I added this description in the ethics box "data is taken from human cell lines, all ethical requirements were taken into consideration when the cell line was generated such as anonymisation to the point that the data generated from this cell line can be used without ethical restriction." I have made a pull request but you can also see the file here: https://github.com/CallumChalmers29/CallumChalmers29-crispy-disco/blob/master/assignments/medsci736-datamanagementplan-ccha939-3.odt. Does that make it clearer?

Thanks
Callum

**Comment by dvasques83** [comment]
Great Callum! It sounds good to me. 
You have done a very nice work throughout the whole course. Congrats!
