### ISSUE TITLE
Final Assignment Review 

### ISSUE THREAD

**Issue by BibianaLee** [UOA-MEDSCI-736/CallumChalmers29-crispy-disco#20]
Hi Callum, 

After reading through your assignment I can tell you that it's well written, thorough and concise. 
You have two minor spelling mistakes in your introduction - you spelt 'occuring' as 'occuring' and 
used 'softwares' instead of 'software' (this has no plural form). Other than that, overall, I am so impressed with your assignment! 

I don't have a background in genetics but I understood your explanations without difficulty, which is great! I loved your use of diagrams to further clarify and support your implementations section. Honestly, I am just blown away by the level of effort you put into your assignment. I will need to re-visit my own assignment because I wasn't nearly as thorough or explicit as you were and maybe I'll add a diagram if I find the time to make one. 

Fix up the spelling mistakes and maybe give it a quick re-read and I think it'll look awesome! 

Kind Regards, 

Bibiana

**Comment by CallumChalmers29** [comment]
Thanks for your great feedback Bibiana :) Both mistakes fixed! I've never written something like this so it was definitely a learning curve!

**Comment by BibianaLee** [comment]
Thank you for fixing ze mistakes :) 
Also yeah it's definitely different from other assignments/reports I've written as well. It's okay your one looks aweeesome 
Closing the issue now 
Good Luck!
