### ISSUE TITLE
Duplicate Team Charter

### ISSUE THREAD

**Issue by tanyagray** [UOA-MEDSCI-736/CallumChalmers29-crispy-disco#4]
Looks like you renamed your team charter and forgot to remove the old one!

**Expected:**
One team charter document

**Actual:**
Two team charters, `team-charter.md` and `medsci736-teamcharter-ccha939-1.md`

**Solution:**
- Remove one team charter
- Pull request the change
- Comment and close this issue

**Comment by CallumChalmers29** [comment]
Thanks for picking that up, I have done the pull request

**Comment by CallumChalmers29** [comment]
Please close this
