### ISSUE TITLE
I hope is  usefull

### ISSUE THREAD

**Issue by Luxo736** [UOA-MEDSCI-736/CallumChalmers29-crispy-disco#9]
-fist lines have “”””   at the  begining is there any specific  function for that?
-line 29 to 32  I dont know  how  clear, welcome and get_user  perform once running the software. Does it  print all together or  inidvidually?  Could you add a  more explicit note?
- line 40 very  interesting, would it  be good  to add in which cases  it will be print help exit  add?. I mean is clear but maybe  the cases  would be good to add.
  -line 96 would  be interested to add a note there?
  -156   have you test that fucntion? It looks  complex and  but  maybe description of booleans would be good to help to undersstand it better.
  -207  lots of additional helps but again  maybe not my projects but i cant really understand why is the aim in this part. Maybe specify a bit would be great.
- 357  i Cant find how is  this working properly  however it seems it is working good.
  Do you relly need all those “ prints” or maybe join all together in just one part? Not sure but could  be a suggestion it did work in mine .. maybe applicable to yours.
- After all your progress seems you are in the right path good for you!

**Comment by CallumChalmers29** [comment]
Hi Luis

-First line I am planning to put a docstring which explains the purpose of the software, I have added that now for you to review

-Lines 29-32 runs individual functions which are commented, for more information on how they work you can look at the comments on the individual functions

-Line 40 will always print the same thing, there are no different cases so nothing to add here

-Line 96, I have added a comment "gets user input for SNP position", is this clear?

-Line 156, yes this function is tested which you can see in my testing module under xxx, I have added comments in lines 163-168 to clarify the boolean expressions

-Line 207, I think the comment is clear as to what the function does, what is not clear for you?

-Line 357, I could join them together and use sep= "\n" but I that makes the one line extremely long and so this method is cleaner

Let me know what you think!

Callum

**Comment by Luxo736** [comment]
I could see you made those changes  and those  look awesome!
   good job!
